In [1]:
import numpy as np
from numpy import genfromtxt #metin dosyasından dizi oluşturur.

In [5]:
data = genfromtxt('bank_note_data.txt', delimiter=',')

In [6]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [8]:
labels = data[:,4]
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [11]:
features = data[:,:4]
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [12]:
X = features
y = labels

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [16]:
from sklearn.preprocessing import MinMaxScaler

In [30]:
scaler_object = MinMaxScaler()
scaler_object.fit(X_train)
scaled_X_train = scaler_object.transform(X_train)
scaled_X_test = scaler_object.transform(X_test)

In [32]:
scaled_X_train

array([[4.44850688e-01, 5.14130449e-01, 2.18194638e-01, 8.50172258e-01],
       [6.53339968e-01, 5.82655745e-01, 9.93242398e-02, 8.17696322e-01],
       [4.81846700e-01, 6.69377018e-01, 3.61193167e-01, 7.63368407e-01],
       ...,
       [4.11050776e-04, 8.63104170e-01, 2.34046756e-01, 3.74261253e-01],
       [2.58284115e-01, 6.16029366e-01, 2.33861752e-01, 7.02643151e-01],
       [2.65661395e-01, 2.44444278e-01, 7.20316361e-01, 7.44775785e-01]])

In [23]:
scaled_X_test

array([[0.62098955, 0.75284662, 0.21900753, 0.5730998 ],
       [0.48778602, 0.82175665, 0.09174727, 0.56211079],
       [0.51158363, 0.77924916, 0.13830875, 0.50392598],
       ...,
       [0.76115065, 0.62415668, 0.27251204, 0.83616757],
       [0.9047516 , 0.90329171, 0.03658247, 0.42267079],
       [0.49296526, 0.86039507, 0.06714046, 0.1622583 ]])

In [33]:
from keras.models import Sequential
from keras.layers import Dense

In [35]:
model = Sequential()

model.add(Dense(4, input_dim=4, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))


In [36]:
model.compile(loss='binary_crossentropy',optimizer='adam', metrics=['accuracy'])

In [37]:
model.fit(scaled_X_train, y_train, batch_size=4, epochs=50, verbose=2)

Epoch 1/50
230/230 - 2s - 11ms/step - accuracy: 0.6921 - loss: 0.6107
Epoch 2/50
230/230 - 0s - 2ms/step - accuracy: 0.8139 - loss: 0.4913
Epoch 3/50
230/230 - 0s - 1ms/step - accuracy: 0.8466 - loss: 0.4183
Epoch 4/50
230/230 - 0s - 2ms/step - accuracy: 0.8727 - loss: 0.3708
Epoch 5/50
230/230 - 1s - 3ms/step - accuracy: 0.8760 - loss: 0.3380
Epoch 6/50
230/230 - 1s - 3ms/step - accuracy: 0.8999 - loss: 0.3057
Epoch 7/50
230/230 - 0s - 2ms/step - accuracy: 0.9021 - loss: 0.2832
Epoch 8/50
230/230 - 0s - 2ms/step - accuracy: 0.9129 - loss: 0.2597
Epoch 9/50
230/230 - 1s - 3ms/step - accuracy: 0.9238 - loss: 0.2423
Epoch 10/50
230/230 - 0s - 2ms/step - accuracy: 0.9336 - loss: 0.2266
Epoch 11/50
230/230 - 1s - 3ms/step - accuracy: 0.9336 - loss: 0.2113
Epoch 12/50
230/230 - 1s - 3ms/step - accuracy: 0.9369 - loss: 0.1977
Epoch 13/50
230/230 - 0s - 1ms/step - accuracy: 0.9434 - loss: 0.1860
Epoch 14/50
230/230 - 0s - 2ms/step - accuracy: 0.9423 - loss: 0.1753
Epoch 15/50
230/230 - 0s - 1

In [43]:
predictions=model.predict(scaled_X_test)

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 


In [45]:
class_labels = (predictions > 0.5).astype("int32")
#class_labels

In [47]:
model.metrics_names

['loss', 'compile_metrics']

In [51]:
from sklearn.metrics import confusion_matrix, classification_report

In [54]:
confusion_matrix(y_test, class_labels)

array([[253,   4],
       [  2, 194]], dtype=int64)

In [56]:
print(classification_report(y_test, class_labels))

              precision    recall  f1-score   support

         0.0       0.99      0.98      0.99       257
         1.0       0.98      0.99      0.98       196

    accuracy                           0.99       453
   macro avg       0.99      0.99      0.99       453
weighted avg       0.99      0.99      0.99       453



In [57]:
model.save('mysupermodel.h5')

In [59]:
from keras.models import load_model

In [60]:
newmodel = load_model('mysupermodel.h5')

In [61]:
newmodel.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                      │ (None, 4)                   │              20 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 8)                   │              40 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 1)                   │               9 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 71 (288.00 B)

 Trainable params: 69 (276.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2 (12.00 B)